<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-04T14:50:36 JST" name="Suite" finished-at="2022-10-04T14:50:36 JST" duration-ms="31">
    <groups>
      <group name="Purchase">
        <method signature="StandaloneTest2.submitOrder(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:frameworkPractice.test.StandaloneTest2@60099951]" name="submitOrder" class="frameworkPractice.test.StandaloneTest2"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2022-10-04T14:50:36 JST" name="Log in Error check" finished-at="2022-10-04T14:50:36 JST" duration-ms="9">
    </test> <!-- Log in Error check -->
    <test started-at="2022-10-04T14:50:36 JST" name="Order number check" finished-at="2022-10-04T14:50:36 JST" duration-ms="31">
      <class name="frameworkPractice.test.StandaloneTest2">
        <test-method signature="submitOrder(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:frameworkPractice.test.StandaloneTest2@60099951]" started-at="2022-10-04T14:50:36 JST" name="submitOrder" data-provider="getData" finished-at="2022-10-04T14:50:36 JST" duration-ms="0" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: C:\Users\JPZ4373\git\SeleniumPracticePageObjectgit\SeleniumPracticePageObject\src\test\java\framePractice\data\data.json (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\JPZ4373\git\SeleniumPracticePageObjectgit\SeleniumPracticePageObject\src\test\java\framePractice\data\data.json (The system cannot find the path specified)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:57)
at org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:157)
at org.testng.internal.Parameters.handleParameters(Parameters.java:791)
at org.testng.internal.Parameters.handleParameters(Parameters.java:728)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:917)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.FileNotFoundException: C:\Users\JPZ4373\git\SeleniumPracticePageObjectgit\SeleniumPracticePageObject\src\test\java\framePractice\data\data.json (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:2388)
at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:2506)
at frameworkPractice.testComponents.globalProperties.getJsonDataToMap(globalProperties.java:48)
at frameworkPractice.test.StandaloneTest2.getData(StandaloneTest2.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:53)
... 19 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
      </class> <!-- frameworkPractice.test.StandaloneTest2 -->
    </test> <!-- Order number check -->
  </suite> <!-- Suite -->
</testng-results>
